-- ============================================================================
-- HP GLOW -> whitelabel tenant seed  (regenerated from CLEAN Supabase CSV exports)
-- Source project: rtsnxmatvbabdylsnuuh. Full descriptions + inclusions restored.
-- Orders/PII intentionally excluded. Vouchers skipped per request.
--
--   * camelCase columns stay double-quoted.  * "priceCents" = PHP pesos x 100.
--   * metadata.variations prices are pesos (display units).
--   * Images point at the old public Supabase bucket (re-host to ImageKit later).
--   * Lab Reports (COA) page must be entitled + toggled on separately (feature flag).
-- ============================================================================

BEGIN;

-- idempotent: remove any prior hpglow tenant first (cascades to products/branding/settings)
DELETE FROM tenants WHERE id = 'hpglow';

INSERT INTO tenants (id, name, slug, status, "planId")
VALUES ('hpglow','HP GLOW','hpglow','active',(SELECT id FROM plans WHERE key = 'pro'));

INSERT INTO tenant_settings (id,"tenantId","storeName",currency)
VALUES ('hpglow-settings','hpglow','HP GLOW','PHP');

INSERT INTO branding (id,"tenantId","logoUrl","themeId",colors,fonts,config)
VALUES ('hpglow-branding','hpglow',NULL,'default','{}'::jsonb,'{}'::jsonb,'{"currency":"PHP","tagline":"Premium pep solutions for radiance, confidence & vitality.","contact":{"instagram":"https://www.instagram.com/hpglowpeptides","viber":"09062349763"},"paymentMethods":[{"id":"gcash","name":"GCash","account":"HP GLOW","number":"09XX XXX XXXX","qrImage":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1764588827991-pfuhkf9k69.jpeg","order":1,"active":true},{"id":"gcash-2","name":"Gcash 2","account":"HP GLOW","number":"09XXXXXXXXX","qrImage":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1764589014648-xigyp23nv8a.jpeg","order":2,"active":false},{"id":"bpi","name":"BPI","account":"HP GLOW","number":"n/a","qrImage":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1764589095410-7eyd6fnwg7.jpeg","order":3,"active":true},{"id":"gotyme","name":"GoTyme Bank","account":"HP GLOW","number":"n/a","qrImage":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1764589167539-c199joy8ise.jpeg","order":4,"active":true},{"id":"credit-card-qrph","name":"Credit Card (QRPH)","account":"High Point Digitals","number":"123****","qrImage":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1777632324923-zh0icxn78tr.jpg","order":5,"active":true}],"coaReports":[{"id":"coa-f4aac3e2","name":"Tirzepatide 30mg","lab":"Janoshik Analytical","date":"2026-01-08","purity":"99.806%","image":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/coa-images/1768501059122-57mti37wt2l.png","link":""},{"id":"coa-7ebe2b99","name":"Tirzepatide 30mg Anaysis Report","lab":"Janoshik Analytical","date":"2026-01-08","purity":"99.806%","image":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/coa-images/1768501502754-nmtlw2f1qwp.png","link":""},{"id":"coa-ca5961db","name":"Tirzepatide 30mg (March COA)","lab":"Janoshik Analytical","date":"2026-03-06","purity":"99.824%","image":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/coa-images/1776142224022-65a4pjij2up.PNG","link":""},{"id":"coa-d4b0d26f","name":"Tirzepatide 30mg Heavy Metals Analysis (March COA)","lab":"Janoshik Analytical","date":"2026-04-14","purity":"99.824%","image":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/coa-images/1776142473608-gc9tkbqnih8.PNG","link":""},{"id":"coa-06eac940","name":"Tirzepatide 30mg (April COA)","lab":"Janoshik Analytical","date":"2026-04-30","purity":"99.854%","image":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/coa-images/1779002284965-khagjb2wbyn.png","link":""},{"id":"coa-40af4d29","name":"Tirzepatide 60mg (April COA)","lab":"Janoshik Analytical","date":"2026-04-30","purity":"99.960%","image":"https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/coa-images/1779002343589-zg7frfr8c9p.png","link":""}]}'::jsonb);

INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-tesamorelin','hpglow','TESAMORELIN','tesamorelin','Tesamorelin',179900,'PHP','𝗧𝗲𝘀𝗮𝗺𝗼𝗿𝗲𝗹𝗶𝗻 is a synthetic analogue of growth hormone-releasing hormone (GHRH) that stimulates the release of human growth hormone (HGH). FDA-approved (not in ph) for 𝗯𝗼𝗱𝘆 𝗳𝗮𝘁 𝗿𝗲𝗱𝗶𝘀𝘁𝗿𝗶𝗯𝘂𝘁𝗶𝗼𝗻 syndrome, Tesamorelin has shown powerful effects on 𝗳𝗮𝘁 𝗹𝗼𝘀𝘀, 𝗺𝘂𝘀𝗰𝗹𝗲 𝗽𝗿𝗲𝘀𝗲𝗿𝘃𝗮𝘁𝗶𝗼𝗻, 𝗻𝗲𝗿𝘃𝗲 𝗿𝗲𝗴𝗲𝗻𝗲𝗿𝗮𝘁𝗶𝗼𝗻, 𝗮𝗻𝗱 𝗰𝗼𝗴𝗻𝗶𝘁𝗶𝘃𝗲 𝗲𝗻𝗵𝗮𝗻𝗰𝗲𝗺𝗲𝗻𝘁.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769338290260-qx8k5tbrsy.jpeg"]'::jsonb,0,'active','{"category":"research","srcId":"1c85d5e0-0952-40ae-8fd3-36e8b8784797","purity":"99.00","storage":"Store at 2°C to 8°C once reconstituted","inclusions":["[𝗜𝗻𝗰𝗹𝘂𝘀𝗶𝗼𝗻𝘀:","•  Syringe for Reconstitution","•  10pcs Sungshim 31g x 8mm Insulin Syringe","•  10pcs Alcohol Pads","•  Tirzepatide Printed Guide","•  Transparent vial case and vial cap","•  Peptide Injection and Inventory Spreadsheet tracker","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","✅ Certificate of Analysis (COA) available","✅ Viber Community (290+ members)","✅ Doctor onboard (you can avail online consultations with her for as low as ₱400)","✅ Community perks","✅ Freebies beyond Tirz, you’ll love!]"],"variations":[{"name":"5mg","price":1799},{"name":"10mg","price":2399}],"variationsMeta":[{"name":"5mg","price":1799,"stock":0,"discountPrice":1399},{"name":"10mg","price":2399,"stock":1,"discountPrice":1899}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-pdrn-cosmetic-grade-topical-use-only','hpglow','PDRNCOSMETICGRAD','pdrn-cosmetic-grade-topical-use-only','PDRN Cosmetic Grade (Topical Use Only)',179900,'PHP','𝗣𝗗𝗥𝗡 (Polydeoxyribonucleotide) is a cosmetic ingredient widely used in skincare formulations to 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝘀𝗸𝗶𝗻 𝗿𝗲𝗻𝗲𝘄𝗮𝗹 𝗮𝗻𝗱 𝗼𝘃𝗲𝗿𝗮𝗹𝗹 𝘀𝗸𝗶𝗻 𝗾𝘂𝗮𝗹𝗶𝘁𝘆. In topical products, it helps 𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝘁𝗵𝗲 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝘀𝗸𝗶𝗻 𝘁𝗲𝘅𝘁𝘂𝗿𝗲, 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝘀 𝗮 𝗵𝗲𝗮𝗹𝘁𝗵𝘆 𝘀𝗸𝗶𝗻 𝗯𝗮𝗿𝗿𝗶𝗲𝗿, 𝗮𝗻𝗱 𝗽𝗿𝗼𝗺𝗼𝘁𝗲𝘀 𝗮 𝗺𝗼𝗿𝗲 𝗿𝗲𝗳𝗿𝗲𝘀𝗵𝗲𝗱, 𝗿𝗮𝗱𝗶𝗮𝗻𝘁-𝗹𝗼𝗼𝗸𝗶𝗻𝗴 𝗰𝗼𝗺𝗽𝗹𝗲𝘅𝗶𝗼𝗻. This cosmetic-grade PDRN is designed strictly for topical use and is commonly added to serums, creams, or ampoules as part of a skincare routine.

For cosmetic and topical use only. Not for injection or internal use.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769340207120-dt4u1iya59p.png"]'::jsonb,1,'active','{"category":"topicals-and-serums","srcId":"f05ddbde-cf23-4c37-b5d9-51b62d4ac600","purity":"99.00","storage":"Store at -20°C"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-ghk-cu-cosmetic-grade-topical-use-only','hpglow','GHKCUCOSMETICGRA','ghk-cu-cosmetic-grade-topical-use-only','GHK-CU Cosmetic Grade (Topical Use Only)',84900,'PHP','𝗚𝗛𝗞-𝗖𝗨 is a well-known copper peptide used in skincare for its 𝘀𝗸𝗶𝗻-𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝗶𝗻𝗴 𝗮𝗻𝗱 𝗿𝗲𝗷𝘂𝘃𝗲𝗻𝗮𝘁𝗶𝗻𝗴 𝗽𝗿𝗼𝗽𝗲𝗿𝘁𝗶𝗲𝘀. In cosmetic formulations, it helps𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝘁𝗵𝗲 𝗹𝗼𝗼𝗸 𝗼𝗳 𝘀𝗸𝗶𝗻 𝘁𝗲𝘅𝘁𝘂𝗿𝗲, 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝘀 𝗮 𝗵𝗲𝗮𝗹𝘁𝗵𝘆 𝘀𝗸𝗶𝗻 𝗯𝗮𝗿𝗿𝗶𝗲𝗿, and promotes a more 𝘆𝗼𝘂𝘁𝗵𝗳𝘂𝗹-𝗹𝗼𝗼𝗸𝗶𝗻𝗴 𝗰𝗼𝗺𝗽𝗹𝗲𝘅𝗶𝗼𝗻. This cosmetic-grade version is designed strictly for topical use and is commonly added to serums, creams, or mists as part of a skincare routine. Ideal for those looking to 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝗳𝗶𝗿𝗺𝗲𝗿-𝗹𝗼𝗼𝗸𝗶𝗻𝗴, 𝘀𝗺𝗼𝗼𝘁𝗵𝗲𝗿, 𝗮𝗻𝗱 𝗺𝗼𝗿𝗲 𝗿𝗮𝗱𝗶𝗮𝗻𝘁 𝘀𝗸𝗶𝗻 𝗼𝘃𝗲𝗿 𝘁𝗶𝗺𝗲.

For cosmetic and topical use only. Not for injection or internal use.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769339253093-7eaq5so1ez6.png"]'::jsonb,5,'active','{"category":"topicals-and-serums","srcId":"15be4b15-b756-4329-a56a-c96b5077ec44","purity":"99.00","discountEnabled":true,"discountPrice":701}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-birthday-flash-bundle-sale','hpglow','BIRTHDAYFLASHBUN','birthday-flash-bundle-sale','BIRTHDAY FLASH BUNDLE SALE!',569900,'PHP','Tirzepatide 60mg + choose your own from GHK-CU 50mg, Glutathione, or NAD+ 500mg. (Please put your choice of peptide under notes)','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1772089755682-m07i3zrwgl.png"]'::jsonb,0,'draft','{"category":"all","srcId":"f1191187-01d0-4d74-955a-f6c7f5813b85","purity":"99.00","storage":"Store at -20°C","freeShipping":true}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-retatrutide-30mg-free-shipping-nationwide','hpglow','RETATRUTIDE30MGF','retatrutide-30mg-free-shipping-nationwide','Retatrutide 30mg (Free Shipping Nationwide)',429900,'PHP','𝗥𝗲𝘁𝗮𝘁𝗿𝘂𝘁𝗶𝗱𝗲 is a next-generation GLP-1 analogue designed to support weight management by reducing appetite and promoting fat loss. It targets visceral and stubborn fat, helping improve body composition and support sustainable weight control. Research Grade Peptide','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766433855825-399qkyckp54.png"]'::jsonb,1,'active','{"category":"all","srcId":"b9d00cd6-f222-43f6-9928-eb0c1d4b39f4","purity":"99.00","storage":"Store at -20°C","freeShipping":true,"discountEnabled":true,"discountPrice":3899}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-sungshim-31g-x-8mm-insulin-syringe','hpglow','SUNGSHIM31GX8MMI','sungshim-31g-x-8mm-insulin-syringe','Sungshim 31g x 8mm Insulin Syringe',1200,'PHP','Sungshim 31g x 8mm Insulin Syringe','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766626711690-imzqkb5w9ps.jpg"]'::jsonb,26,'active','{"category":"supplies","srcId":"9746f0b7-4f5c-4b08-bc41-bdaad312430f","purity":"99.00","storage":"Store at -20°C"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-ghk-cu','hpglow','GHKCU','ghk-cu','GHK-CU',119900,'PHP','𝗚𝗛𝗞-𝗖𝘂 (𝗖𝗼𝗽𝗽𝗲𝗿 𝗣𝗲𝗽𝘁𝗶𝗱𝗲) is a premium bioactive peptide known for its 𝗽𝗼𝘄𝗲𝗿𝗳𝘂𝗹 𝘀𝗸𝗶𝗻-𝗿𝗲𝗴𝗲𝗻𝗲𝗿𝗮𝘁𝗶𝗻𝗴 𝗮𝗻𝗱 𝗮𝗻𝘁𝗶-𝗮𝗴𝗶𝗻𝗴 𝗯𝗲𝗻𝗲𝗳𝗶𝘁𝘀. Used in advanced aesthetic treatments, it supports 𝗰𝗼𝗹𝗹𝗮𝗴𝗲𝗻 𝗽𝗿𝗼𝗱𝘂𝗰𝘁𝗶𝗼𝗻, 𝗶𝗺𝗽𝗿𝗼𝘃𝗲𝘀 𝘀𝗸𝗶𝗻 𝗳𝗶𝗿𝗺𝗻𝗲𝘀𝘀, 𝗮𝗻𝗱 𝗲𝗻𝗵𝗮𝗻𝗰𝗲𝘀 𝗼𝘃𝗲𝗿𝗮𝗹𝗹 𝘁𝗼𝗻𝗲 𝗮𝗻𝗱 𝘁𝗲𝘅𝘁𝘂𝗿𝗲 for a visibly rejuvenated appearance. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766434820735-29nxomdz57b.png"]'::jsonb,0,'active','{"category":"cosmetic","srcId":"9c9ab6d9-3f55-4907-8681-5884631b43a3","purity":"99.00","storage":"Store at -20°C","featured":true,"inclusions":["[Syringe for Reconstitution","Sungshim 31g x 8mm Insulin Syringe: 10pcs (50mg) and 20pcs (100mg)","10pcs Alcohol Pads","GHK-CU Printed Guide","Transparent vial case and vial cap","FREE Black Peptide Vial Case","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Certificate of Analysis (COA) available","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"],"variations":[{"name":"50mg","price":1199},{"name":"100mg","price":1850}],"variationsMeta":[{"name":"50mg","price":1199,"stock":1,"discountPrice":999},{"name":"100mg","price":1850,"stock":9}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-glutathione','hpglow','GLUTATHIONE','glutathione','Glutathione',149900,'PHP','𝗚𝗹𝘂𝘁𝗮𝘁𝗵𝗶𝗼𝗻𝗲 is a 𝗽𝗿𝗲𝗺𝗶𝘂𝗺 𝗮𝗻𝘁𝗶𝗼𝘅𝗶𝗱𝗮𝗻𝘁 widely known for 𝘀𝗸𝗶𝗻 𝗯𝗿𝗶𝗴𝗵𝘁𝗲𝗻𝗶𝗻𝗴 𝗮𝗻𝗱 𝗼𝘃𝗲𝗿𝗮𝗹𝗹 𝘀𝗸𝗶𝗻 𝗿𝗲𝘃𝗶𝘁𝗮𝗹𝗶𝘇𝗮𝘁𝗶𝗼𝗻. Best known for its powerful detoxifying properties, it helps promote a clearer, more even complexion and 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝘀 𝗮 𝗵𝗲𝗮𝗹𝘁𝗵𝘆, 𝗿𝗮𝗱𝗶𝗮𝗻𝘁 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766626085984-goh4gkej4c6.png"]'::jsonb,28,'active','{"category":"cosmetic","srcId":"c59f7e6e-656a-4c14-b208-5ca40ee78efa","purity":"99.00","storage":"Store at -20°C","featured":true,"discountEnabled":true,"discountPrice":999,"inclusions":["[Syringe for Reconstitution - 1pc","Terumo Insulin Syringe 30g x 3/8\" - 7pcs","10pcs Alcohol Pads","Glutathione Printed Guide","Vial cap","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"],"variations":[{"name":"1500mg","price":1499}],"variationsMeta":[{"name":"1500mg","price":1499,"stock":4,"discountPrice":999}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-fat-blaster-lipo-c','hpglow','FATBLASTERLIPOC','fat-blaster-lipo-c','Fat Blaster Lipo-C',239900,'PHP','A carefully formulated lipotropic blend designed to support metabolic function and overall wellness. Each ingredient is selected to work alongside your body’s natural processes, making it a popular choice for those focusing on structured health and lifestyle routines. This combination includes essential amino acids, vitamins, and coenzymes commonly associated with energy metabolism, nutrient processing, and cellular support. L-Carnitine plays a role in fatty acid transport, while Methionine, Inositol, and Choline are known as lipotropic agents often used in wellness-focused protocols. B vitamins and NADH contribute to energy production pathways within the body.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1775976637299-0tjqd5efp0o.png"]'::jsonb,1,'active','{"category":"all","srcId":"5a8a3e54-dbf3-42fb-bdd2-3d9def72a262","purity":"99.00","discountEnabled":true,"discountPrice":1999}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-glow-sculpt-duo-tirzepatide-15mg-ghk-cu-50mg','hpglow','GLOWSCULPTDUOTIR','glow-sculpt-duo-tirzepatide-15mg-ghk-cu-50mg','Glow Sculpt Duo (Tirzepatide 15mg & GHK-CU 50mg)',369800,'PHP','The 𝗚𝗹𝗼𝘄 𝗦𝗰𝘂𝗹𝗽𝘁 𝗕𝘂𝗻𝗱𝗹𝗲 combines two peptides commonly used in wellness and metabolic support protocols.

𝗧𝗶𝗿𝘇𝗲𝗽𝗮𝘁𝗶𝗱𝗲 works on GLP-1 and GIP receptors, helping regulate appetite, slow gastric emptying, and support blood sugar control.

𝗚𝗛𝗞-𝗖𝘂 (Copper Peptide) is known for its role in skin repair and regeneration, supporting collagen production, tissue healing, and overall skin health.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773322270052-t3r5ijpk8k.png"]'::jsonb,5,'active','{"category":"all","srcId":"73cc4752-53ed-4034-8238-0d73e2769f60","purity":"99.00","storage":"Store at -20°C","discountEnabled":true,"discountPrice":3299}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-cagrilintide','hpglow','CAGRILINTIDE','cagrilintide','Cagrilintide',179900,'PHP','𝗖𝗮𝗴𝗿𝗶𝗹𝗶𝗻𝘁𝗶𝗱𝗲 is a peptide-based GLP-1 analogue designed to 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝘄𝗲𝗶𝗴𝗵𝘁 𝗺𝗮𝗻𝗮𝗴𝗲𝗺𝗲𝗻𝘁 by helping 𝗿𝗲𝗱𝘂𝗰𝗲 𝗮𝗽𝗽𝗲𝘁𝗶𝘁𝗲 𝗮𝗻𝗱 𝗰𝗼𝗻𝘁𝗿𝗼𝗹 𝗳𝗼𝗼𝗱 𝗶𝗻𝘁𝗮𝗸𝗲. It targets visceral and stubborn fat, promoting improved body composition and supporting overall fat loss. Commonly known as "𝙂𝙇𝙋-1 𝘽𝙤𝙤𝙨𝙩𝙚𝙧". Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766624826888-38ofy94ib5q.png"]'::jsonb,0,'active','{"category":"research","srcId":"207f2e4d-0f1a-4e8d-89cf-1576a1a717d8","purity":"99.00","storage":"Store at -20°C","variations":[{"name":"5mg","price":1799},{"name":"10mg","price":2299}],"variationsMeta":[{"name":"5mg","price":1799,"stock":3},{"name":"10mg","price":2299,"stock":0}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-pt-141','hpglow','PT141','pt-141','PT-141',149900,'PHP','PT-141 (Bremelanotide) is a peptide designed to support sexual health and enhance libido in both men and women. It works by stimulating natural pathways linked to sexual arousal, helping improve desire, responsiveness, and overall sexual vitality. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766626600078-1hpeuvnu5ovi.png"]'::jsonb,100,'active','{"category":"wellness","srcId":"18c8b138-dbf0-4cfb-bf96-13a67252c91f","purity":"99.00","molecularWeight":"1025.19 g/mol","cas":"189691-06-3","sequence":"Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-OH","storage":"Store at -20°C. Reconstituted solution at 2-8°C for up to 30 days.","variations":[{"name":"10mg","price":1499}],"variationsMeta":[{"name":"10mg","price":1499,"stock":2,"discountPrice":999}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-selank','hpglow','SELANK','selank','Selank',149900,'PHP','Selank is a peptide designed to support mental well-being, focus, and stress management. It helps promote a calm, balanced state while enhancing cognitive clarity and emotional resilience. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766627072044-wwgdoy7bdm.png"]'::jsonb,0,'active','{"category":"wellness","srcId":"2ba68156-7b68-43ce-8d80-df4cdf15a347","purity":"99.00","storage":"Store at -20°C","variations":[{"name":"5mg","price":1499},{"name":"10mg","price":1799}],"variationsMeta":[{"name":"5mg","price":1499,"stock":0,"discountPrice":799},{"name":"10mg","price":1799,"stock":2,"discountPrice":1499}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-semax','hpglow','SEMAX','semax','Semax',139900,'PHP','𝗦𝗲𝗺𝗮𝘅 is a neuroactive peptide designed to 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝗳𝗼𝗰𝘂𝘀, 𝗺𝗲𝗻𝘁𝗮𝗹 𝗰𝗹𝗮𝗿𝗶𝘁𝘆, 𝗮𝗻𝗱 𝗰𝗼𝗴𝗻𝗶𝘁𝗶𝘃𝗲 𝗽𝗲𝗿𝗳𝗼𝗿𝗺𝗮𝗻𝗰𝗲. It is ideal for individuals seeking improved concentration, sharper thinking, and better mental resilience, particularly during periods of high cognitive demand or stress. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766626990312-uf80l2sam4b.png"]'::jsonb,0,'active','{"category":"wellness","srcId":"79c6094c-8045-4b7f-95da-dae98ca31dde","purity":"98.80","storage":"Store at -20°C","inclusions":["[Syringe for Reconstitution","Sungshim 31g x 8mm Insulin Syringe: 10pcs (5mg) and 16pcs (10mg)","10pcs (100mg) and 20pcs (500mg) Alcohol Pads","SEMAX+ Printed Guide","Transparent vial case and vial cap","FREE Black Peptide Vial Case 3ml","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"],"variations":[{"name":"5mg","price":1399},{"name":"10mg","price":1699}],"variationsMeta":[{"name":"5mg","price":1399,"stock":6,"discountPrice":999},{"name":"10mg","price":1699,"stock":0}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-thymosin-alpha-1','hpglow','THYMOSINALPHA1','thymosin-alpha-1','Thymosin Alpha-1',109900,'PHP','𝗧𝗵𝘆𝗺𝗼𝘀𝗶𝗻 𝗔𝗹𝗽𝗵𝗮-𝟭 (often abbreviated as TA1 or Ta1) is a naturally occurring peptide produced by the thymus gland. Composed of 𝟮𝟴 𝗮𝗺𝗶𝗻𝗼 𝗮𝗰𝗶𝗱𝘀, its primary function is to 𝗲𝗻𝗵𝗮𝗻𝗰𝗲 𝗶𝗺𝗺𝘂𝗻𝗲 𝘀𝘆𝘀𝘁𝗲𝗺 𝗽𝗲𝗿𝗳𝗼𝗿𝗺𝗮𝗻𝗰𝗲 by stimulating key immune cells and processes.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769043180174-97i3s7fv2jc.png"]'::jsonb,0,'active','{"category":"wellness","srcId":"77a47667-0d23-4854-a9db-aa478837dece","purity":"99.00","variations":[{"name":"5mg","price":1099},{"name":"10mg","price":2099}],"variationsMeta":[{"name":"5mg","price":1099,"stock":2},{"name":"10mg","price":2099,"stock":2}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-snap-8-topical-use-only','hpglow','SNAP8TOPICALUSEO','snap-8-topical-use-only','Snap-8 (Topical Use Only)',99900,'PHP','𝗦𝗻𝗮𝗽-𝟴 is a synthetic peptide that 𝗺𝗶𝗺𝗶𝗰𝘀 𝘁𝗵𝗲 𝗲𝗳𝗳𝗲𝗰𝘁𝘀 𝗼𝗳 𝗕𝗼𝘁𝗼𝘅. It is used to 𝗿𝗲𝗱𝘂𝗰𝗲 𝘁𝗵𝗲 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝘄𝗿𝗶𝗻𝗸𝗹𝗲𝘀 𝗮𝗻𝗱 𝗲𝘅𝗽𝗿𝗲𝘀𝘀𝗶𝗼𝗻 𝗹𝗶𝗻𝗲𝘀 by inhibiting acetylcholine, which relaxes the facial muscles and reduces the signals sent to those muscles by neurotransmitters. Snap-8 also 𝗽𝗿𝗼𝗺𝗼𝘁𝗲𝘀 𝗰𝗼𝗹𝗹𝗮𝗴𝗲𝗻 𝘀𝘆𝗻𝘁𝗵𝗲𝘀𝗶𝘀, 𝗶𝗺𝗽𝗿𝗼𝘃𝗲𝘀 𝘀𝗸𝗶𝗻 𝗲𝗹𝗮𝘀𝘁𝗶𝗰𝗶𝘁𝘆, 𝗮𝗻𝗱 𝗵𝘆𝗱𝗿𝗮𝘁𝗲𝘀 𝗮𝗻𝗱 𝗻𝗼𝘂𝗿𝗶𝘀𝗵𝗲𝘀 𝘁𝗵𝗲 𝘀𝗸𝗶𝗻.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769338726217-aa09yk2itk.png"]'::jsonb,0,'draft','{"category":"topicals-and-serums","srcId":"4f6bad50-f544-4006-ba84-ba444681cb6f","purity":"99.00","storage":"Store at -20°C (unreconstituted)"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-glow-bpc-157-ghk-cu-tb500-70mg','hpglow','GLOWBPC157GHKCUT','glow-bpc-157-ghk-cu-tb500-70mg','Glow (BPC-157, GHK-CU, TB500) 70mg',289900,'PHP','𝗚𝗹𝗼𝘄 𝗣𝗲𝗽𝘁𝗶𝗱𝗲 is a carefully formulated peptide blend designed for those 𝗳𝗼𝗰𝘂𝘀𝗲𝗱 𝗼𝗻 𝗿𝗲𝗰𝗼𝘃𝗲𝗿𝘆, 𝗿𝗲𝗴𝗲𝗻𝗲𝗿𝗮𝘁𝗶𝗼𝗻, 𝗮𝗻𝗱 𝗼𝘃𝗲𝗿𝗮𝗹𝗹 𝗰𝗲𝗹𝗹𝘂𝗹𝗮𝗿 𝘀𝘂𝗽𝗽𝗼𝗿𝘁. This advanced combination of BPC-157, GHK-Cu, and TB-500 is known in research settings for 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝗶𝗻𝗴 𝘁𝗶𝘀𝘀𝘂𝗲 𝗿𝗲𝗽𝗮𝗶𝗿, 𝘀𝗸𝗶𝗻 𝗾𝘂𝗮𝗹𝗶𝘁𝘆, 𝗮𝗻𝗱 𝗺𝘂𝘀𝗰𝗹𝗲 𝗿𝗲𝗰𝗼𝘃𝗲𝗿𝘆 at a cellular level.

Ideal for individuals who prioritize performance, skin vitality, and recovery, Glow is often chosen as part of a structured wellness or research-based protocol. 

✨ Glow from the inside out
🧬 Recovery-focused peptide blend
⚡ Supports skin, muscle, and tissue renewal

For research and educational purposes only. Not intended to diagnose, treat, cure, or prevent any disease.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769340494172-m30sjy604k8.png"]'::jsonb,3,'active','{"category":"all","srcId":"b81535b9-4b86-42d4-8867-589bbada2113","purity":"99.00","molecularWeight":"70mg","storage":"Store at -20°C"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-glow-bpc-157-ghk-cu-tb500','hpglow','GLOWBPC157GHKCUT-2','glow-bpc-157-ghk-cu-tb500','GLOW (BPC-157, GHK-CU, TB500)',289900,'PHP','Premium blend of BPC-157, GHK-CU, and TB500 peptides. Complete recovery and regenerative peptide combination.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766434887907-if0ggjkava.png"]'::jsonb,0,'draft','{"category":"wellness","srcId":"29d3b580-77e8-4c70-b306-4bb7f4ec857c","purity":"99.00","storage":"Store at -20°C","variations":[{"name":"70mg","price":2899}],"variationsMeta":[{"name":"70mg","price":2899,"stock":1}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-lipo-c-with-b12','hpglow','LIPOCWITHB12','lipo-c-with-b12','Lipo-C with B12',169900,'PHP','Lipo-C with B12 is a fat-metabolism support formula designed to help boost energy, support fat breakdown, and promote overall body vitality. Enriched with vitamin B12, it aids in energy production while helping optimize your body’s natural fat-burning processes. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766627187213-y7ueqhpcmu9.png"]'::jsonb,1,'active','{"category":"research","srcId":"fad4d356-6838-4a8e-b0e8-8cc02adbd7b5","purity":"99.00","storage":"Store at room temperature","variations":[{"name":"10ml","price":1699}],"variationsMeta":[{"name":"10ml","price":1699,"stock":2}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-lemon-bottle','hpglow','LEMONBOTTLE','lemon-bottle','Lemon Bottle',129900,'PHP','𝗟𝗲𝗺𝗼𝗻 𝗕𝗼𝘁𝘁𝗹𝗲 (𝗙𝗮𝘁 𝗗𝗶𝘀𝘀𝗼𝗹𝘃𝗶𝗻𝗴 𝗦𝗼𝗹𝘂𝘁𝗶𝗼𝗻) is a non-surgical fat-dissolving solution 𝗱𝗲𝘀𝗶𝗴𝗻𝗲𝗱 𝘁𝗼 𝘁𝗮𝗿𝗴𝗲𝘁 𝘀𝘁𝘂𝗯𝗯𝗼𝗿𝗻, 𝗹𝗼𝗰𝗮𝗹𝗶𝘇𝗲𝗱 𝗳𝗮𝘁 𝗶𝗻 𝗮𝗿𝗲𝗮𝘀 like the chin, abdomen, arms, and thighs. It contains active ingredients such as riboflavin (Vitamin B2), bromelain, and lecithin, which work together to help break down fat cells so the body can naturally process and eliminate them over time. It’s commonly 𝘂𝘀𝗲𝗱 𝗳𝗼𝗿 𝗯𝗼𝗱𝘆 𝗰𝗼𝗻𝘁𝗼𝘂𝗿𝗶𝗻𝗴 𝘄𝗵𝗲𝗿𝗲 𝗳𝗮𝘁 𝗶𝘀 𝗿𝗲𝘀𝗶𝘀𝘁𝗮𝗻𝘁 to diet and lifestyle changes. 𝗥𝗲𝘀𝘂𝗹𝘁𝘀 𝗱𝗲𝘃𝗲𝗹𝗼𝗽 𝗴𝗿𝗮𝗱𝘂𝗮𝗹𝗹𝘆 𝗮𝗻𝗱 𝗺𝗮𝘆 𝗿𝗲𝗾𝘂𝗶𝗿𝗲 𝗺𝘂𝗹𝘁𝗶𝗽𝗹𝗲 𝘀𝗲𝘀𝘀𝗶𝗼𝗻𝘀 depending on individual goals and the treatment area. 𝙄𝙢𝙥𝙤𝙧𝙩𝙖𝙣𝙩 𝙉𝙤𝙩𝙚: 𝘽𝙚𝙨𝙩 𝙖𝙙𝙢𝙞𝙣𝙞𝙨𝙩𝙚𝙧𝙚𝙙 𝙗𝙮 𝙖 𝙦𝙪𝙖𝙡𝙞𝙛𝙞𝙚𝙙 𝙥𝙧𝙤𝙛𝙚𝙨𝙨𝙞𝙤𝙣𝙖𝙡 𝙨𝙪𝙘𝙝 𝙖𝙨 𝙖𝙣 𝙖𝙚𝙨𝙩𝙝𝙚𝙩𝙞𝙘𝙞𝙖𝙣, 𝙣𝙪𝙧𝙨𝙚, 𝙤𝙧 𝙙𝙤𝙘𝙩𝙤𝙧 𝙩𝙤 𝙚𝙣𝙨𝙪𝙧𝙚 𝙨𝙖𝙛𝙚𝙩𝙮 𝙖𝙣𝙙 𝙥𝙧𝙤𝙥𝙚𝙧 𝙩𝙚𝙘𝙝𝙣𝙞𝙦𝙪𝙚.
','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766627165597-jod4dr4fts.png"]'::jsonb,17,'active','{"category":"face-body-contouring","srcId":"cbb2ac6a-a134-46ce-a2c3-921c83c0d76a","purity":"99.00","storage":"Store at room temperature","featured":true,"inclusions":["[10pcs Sungshim 31g x 8mm Insulin Syringe","Transparent vial case","Vial Opener","Skin Marker and Ruler White","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Certificate of Analysis (COA) available for tirz","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"],"variations":[{"name":"10ml","price":1299}],"variationsMeta":[{"name":"10ml","price":1299,"stock":7,"discountPrice":999}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-nad','hpglow','NAD','nad','NAD+',129900,'PHP','𝗡𝗔𝗗+ (𝗡𝗶𝗰𝗼𝘁𝗶𝗻𝗮𝗺𝗶𝗱𝗲 𝗔𝗱𝗲𝗻𝗶𝗻𝗲 𝗗𝗶𝗻𝘂𝗰𝗹𝗲𝗼𝘁𝗶𝗱𝗲) is a premium bioactive compound essential for 𝗰𝗲𝗹𝗹𝘂𝗹𝗮𝗿 𝗲𝗻𝗲𝗿𝗴𝘆, 𝗿𝗲𝗽𝗮𝗶𝗿, 𝗮𝗻𝗱 𝗹𝗼𝗻𝗴𝗲𝘃𝗶𝘁𝘆. Widely used in advanced wellness and aesthetic protocols, it supports 𝗶𝗺𝗽𝗿𝗼𝘃𝗲𝗱 𝘃𝗶𝘁𝗮𝗹𝗶𝘁𝘆, 𝗲𝗻𝗵𝗮𝗻𝗰𝗲𝗱 𝗰𝗲𝗹𝗹𝘂𝗹𝗮𝗿 𝗳𝘂𝗻𝗰𝘁𝗶𝗼𝗻, 𝗮𝗻𝗱 𝗼𝘃𝗲𝗿𝗮𝗹𝗹 𝗿𝗲𝗷𝘂𝘃𝗲𝗻𝗮𝘁𝗶𝗼𝗻 𝗳𝗿𝗼𝗺 𝘄𝗶𝘁𝗵𝗶𝗻. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766433789611-20ii0sd19cb.png"]'::jsonb,0,'active','{"category":"wellness","srcId":"65e8dc8c-b26a-418c-aa2d-40cf6ec59808","purity":"99.50","storage":"Store at -20°C","featured":true,"inclusions":["[Syringe for Reconstitution","Sungshim 31g x 8mm Insulin Syringe: 10pcs (100mg) and 20pcs (500mg) Alcohol Pads","NAD+ Printed Guide","Transparent vial case and vial cap","FREE Black Peptide Vial Case 10ml","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Certificate of Analysis (COA) available","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"],"variations":[{"name":"100mg","price":1299},{"name":"500mg","price":2199}],"variationsMeta":[{"name":"100mg","price":1299,"stock":0},{"name":"500mg","price":2199,"stock":2}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-kisspeptin','hpglow','KISSPEPTIN','kisspeptin','Kisspeptin',169900,'PHP','𝗞𝗶𝘀𝘀𝗽𝗲𝗽𝘁𝗶𝗻 is a peptide that 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝘀 𝘀𝗲𝘅𝘂𝗮𝗹 𝗵𝗲𝗮𝗹𝘁𝗵 by helping regulate hormones linked to libido and reproductive function. It may help 𝗲𝗻𝗵𝗮𝗻𝗰𝗲 𝘀𝗲𝘅𝘂𝗮𝗹 𝘃𝗶𝘁𝗮𝗹𝗶𝘁𝘆 and promote healthy endocrine balance. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766625201103-no41bb27ofi.png"]'::jsonb,0,'active','{"category":"wellness","srcId":"86d02413-d2c2-4c0e-a26f-d95dc29446d8","purity":"99.00","storage":"Store at -20°C","variations":[{"name":"5mg","price":1699},{"name":"10mg","price":2399}],"variationsMeta":[{"name":"5mg","price":1699,"stock":2,"discountPrice":899},{"name":"10mg","price":2399,"stock":2}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-ahk-cu-cosmetic-grade-topical-use-only','hpglow','AHKCUCOSMETICGRA','ahk-cu-cosmetic-grade-topical-use-only','AHK-CU Cosmetic Grade (Topical Use Only)',128000,'PHP','𝗔𝗛𝗞-𝗖𝗨 is a copper peptide used in cosmetic hair and scalp formulas to 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝗮 𝗵𝗲𝗮𝗹𝘁𝗵𝗶𝗲𝗿-𝗹𝗼𝗼𝗸𝗶𝗻𝗴 𝘀𝗰𝗮𝗹𝗽 𝗮𝗻𝗱 𝗳𝘂𝗹𝗹𝗲𝗿-𝗹𝗼𝗼𝗸𝗶𝗻𝗴 𝗵𝗮𝗶𝗿. It’s often added to scalp serums, hair tonics, or leave-on treatments to 𝗵𝗲𝗹𝗽 𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝘁𝗵𝗲 𝗹𝗼𝗼𝗸 𝗼𝗳 𝗵𝗮𝗶𝗿 𝗱𝗲𝗻𝘀𝗶𝘁𝘆 𝗮𝗻𝗱 𝗼𝘃𝗲𝗿𝗮𝗹𝗹 𝗵𝗮𝗶𝗿 𝘃𝗶𝘁𝗮𝗹𝗶𝘁𝘆. This cosmetic-grade version is intended strictly for topical use and is best used as part of a consistent hair care routine.

For cosmetic and topical use only. Not for injection or internal use.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769339818484-ijw11jgjb2.png"]'::jsonb,4,'active','{"category":"topicals-and-serums","srcId":"d59a3b4a-e74c-45c2-81a0-a97886a33bb9","purity":"99.00","storage":"Store at -20°C","discountEnabled":true,"discountPrice":699}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-retatrutide','hpglow','RETATRUTIDE','retatrutide','Retatrutide',349900,'PHP','Triple agonist peptide for metabolic research. Research-grade peptide for weight management studies.','[]'::jsonb,0,'draft','{"category":"research","srcId":"8e990c67-16ea-4e4b-90b2-0aeb9653be27","purity":"99.50","storage":"Store at -20°C","featured":true,"variations":[{"name":"15mg","price":3499},{"name":"20mg","price":3499},{"name":"30mg","price":4299}],"variationsMeta":[{"name":"15mg","price":3499,"stock":0},{"name":"20mg","price":3499,"stock":0},{"name":"30mg","price":4299,"stock":0}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-tirzepatide','hpglow','TIRZEPATIDE','tirzepatide','Tirzepatide',249900,'PHP','𝗧𝗜𝗥𝗭𝗘𝗣𝗔𝗧𝗜𝗗𝗘 is a GLP-1–based weight-loss medication 𝗱𝗲𝘀𝗶𝗴𝗻𝗲𝗱 𝘁𝗼 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝗮𝗽𝗽𝗲𝘁𝗶𝘁𝗲 𝗰𝗼𝗻𝘁𝗿𝗼𝗹 𝗮𝗻𝗱 𝗿𝗲𝗱𝘂𝗰𝗲𝗱 𝗳𝗼𝗼𝗱 𝗶𝗻𝘁𝗮𝗸𝗲. By mimicking natural hormones involved in hunger regulation, it helps promote feelings of fullness and 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝘀 𝘀𝘂𝘀𝘁𝗮𝗶𝗻𝗮𝗯𝗹𝗲 𝘄𝗲𝗶𝗴𝗵𝘁 𝗹𝗼𝘀𝘀 when used under medical supervision.
‎
Ideal for individuals seeking structured support with weight management and metabolic health. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766432919623-sjzdawaxlo7.png"]'::jsonb,100,'active','{"category":"research","srcId":"0e7af607-affa-4c40-8ce9-3d23bffbe53a","purity":"99.81","molecularWeight":"31.23mg","cas":"2026788-19-2","sequence":"Proprietary","storage":"Store at -20°C for long-term storage. Reconstituted solution should be stored at 2-8°C.","featured":true,"inclusions":["[Syringe for Reconstitution","Sungshim 31g x 8mm Insulin Syringe: 6pcs (15mg and 20mg), 7pcs (30mg), and 10pcs (60mg)","Tirzepatide Printed Guide","Transparent vial case and vial cap","FREE Black Peptide Vial Case 3ml for 60mg","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Certificate of Analysis (COA) available","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"],"variations":[{"name":"15mg","price":2499},{"name":"20mg","price":2899},{"name":"30mg","price":3499}],"variationsMeta":[{"name":"15mg","price":2499,"stock":1},{"name":"20mg","price":2899,"stock":7},{"name":"30mg","price":3499,"stock":5}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-whitening-spot-fading-skinbooster','hpglow','WHITENINGSPOTFAD','whitening-spot-fading-skinbooster','Whitening & Spot-Fading Skinbooster',48900,'PHP','𝗪𝗵𝗶𝘁𝗲𝗻𝗶𝗻𝗴 & 𝗦𝗽𝗼𝘁-𝗙𝗮𝗱𝗶𝗻𝗴 𝗦𝗸𝗶𝗻𝗯𝗼𝗼𝘀𝘁𝗲𝗿 is a topical brightening concentrate f𝗳𝗼𝗿𝗺𝘂𝗹𝗮𝘁𝗲𝗱 𝘄𝗶𝘁𝗵 𝗡𝗶𝗮𝗰𝗶𝗻𝗮𝗺𝗶𝗱𝗲, 𝗚𝗹𝘂𝘁𝗮𝘁𝗵𝗶𝗼𝗻𝗲, 𝗩𝗶𝘁𝗮𝗺𝗶𝗻 𝗖, 𝗮𝗻𝗱 𝗣𝗗𝗥𝗡 to help 𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝘂𝗻𝗲𝘃𝗲𝗻 𝘀𝗸𝗶𝗻 𝘁𝗼𝗻𝗲, 𝗿𝗲𝗱𝘂𝗰𝗲 𝘁𝗵𝗲 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗱𝗮𝗿𝗸 𝘀𝗽𝗼𝘁𝘀, 𝗮𝗻𝗱 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝗵𝗲𝗮𝗹𝘁𝗵𝗶𝗲𝗿-𝗹𝗼𝗼𝗸𝗶𝗻𝗴 𝘀𝗸𝗶𝗻. Designed to be mixed with your facial serum, moisturizer, or body lotion, it enhances your existing skincare routine while supporting hydration, repair, and a more radiant glow. For topical cosmetic use only.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769853744472-abbk1ooe7go.png"]'::jsonb,4,'active','{"category":"topicals-and-serums","srcId":"244a00b3-66e2-4054-9ff0-8ea85f83d858","purity":"99.00","molecularWeight":"3ml","storage":"Store at -20°C"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-tirzepatide-60mg-free-shipping-nationwide','hpglow','TIRZEPATIDE60MGF','tirzepatide-60mg-free-shipping-nationwide','Tirzepatide 60mg (Free Shipping Nationwide)',569900,'PHP','𝗧𝗜𝗥𝗭𝗘𝗣𝗔𝗧𝗜𝗗𝗘 is a GLP-1–based weight-loss medication 𝗱𝗲𝘀𝗶𝗴𝗻𝗲𝗱 𝘁𝗼 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝗮𝗽𝗽𝗲𝘁𝗶𝘁𝗲 𝗰𝗼𝗻𝘁𝗿𝗼𝗹 𝗮𝗻𝗱 𝗿𝗲𝗱𝘂𝗰𝗲𝗱 𝗳𝗼𝗼𝗱 𝗶𝗻𝘁𝗮𝗸𝗲. By mimicking natural hormones involved in hunger regulation, it helps promote feelings of fullness and 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝘀 𝘀𝘂𝘀𝘁𝗮𝗶𝗻𝗮𝗯𝗹𝗲 𝘄𝗲𝗶𝗴𝗵𝘁 𝗹𝗼𝘀𝘀 when used under medical supervision.
‎
Ideal for individuals seeking structured support with weight management and metabolic health. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769416025786-n55pc3ebp1m.png"]'::jsonb,1,'active','{"category":"research","srcId":"9f414c25-7398-4065-9084-8e543cad3d1f","purity":"99.81","molecularWeight":"31.23mg","cas":"2026788-19-2","storage":"Store at -20°C for long-term storage. Reconstituted solution should be stored at 2-8°C.","freeShipping":true,"inclusions":["[Syringe for Reconstitution","Sungshim 31g x 8mm Insulin Syringe: 10pcs (60mg)","Tirzepatide Printed Guide","Transparent vial case and vial cap","FREE Black Peptide Vial Case 3ml for 60mg","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Certificate of Analysis (COA) available","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-the-glow-slim-duo-tirzepatide-60mg-ghk-cu-50mg-set','hpglow','THEGLOWSLIMDUOTI','the-glow-slim-duo-tirzepatide-60mg-ghk-cu-50mg-set','THE GLOW + SLIM DUO (Tirzepatide 60mg & GHK-CU 50mg Set)',569900,'PHP','THE GLOW + SLIM DUO
Tirzepatide 60 mg + GHK-CU 50 mg
₱5,699 with FREE shipping nationwide
 ㅤㅤㅤㅤㅤㅤ
What each one is for:
 ㅤㅤㅤㅤㅤㅤ
Tirzepatide (Tirze)
• Helps support appetite control and cravings
• Supports blood sugar regulation (used medically for type 2 diabetes)
• Used for weight management in appropriate patients under clinician guidance
 ㅤㅤㅤㅤㅤㅤ
GHK-CU
• Supports skin repair and a healthier-looking glow
• Helps support collagen and skin elasticity
• Often used for skin texture, fine lines, and overall skin recovery support','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1768454653873-6q70upkv1o9.png"]'::jsonb,0,'draft','{"category":"all","srcId":"36bd230b-2ca4-4a05-a73c-e20c7507c499","purity":"99.00","storage":"Store at -20°C","freeShipping":true,"inclusions":["[Syringe for Reconstitution","Sungshim 31g x 8mm Insulin Syringe: 10pcs (Tirze 60mg) and 10pcs (GHK-CU 50mg)","Tirzepatide & GHK-CU Printed Guides","Transparent vial case and vial cap","FREE Black Peptide Vial Case 3ml and 10ml","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Certificate of Analysis (COA) available","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-ghk-cu-kpv-blend-60mg','hpglow','GHKCUKPVBLEND60M','ghk-cu-kpv-blend-60mg','GHK-CU + KPV Blend 60mg',189900,'PHP','𝗥𝗲𝗽𝗮𝗶𝗿 𝗦𝘂𝗽𝗽𝗼𝗿𝘁 + 𝗖𝗮𝗹𝗺𝗶𝗻𝗴 𝗕𝗮𝗹𝗮𝗻𝗰𝗲 𝗳𝗼𝗿 𝗛𝗲𝗮𝗹𝘁𝗵𝗶𝗲𝗿-𝗟𝗼𝗼𝗸𝗶𝗻𝗴 𝗦𝗸𝗶𝗻

A 𝗱𝘂𝗮𝗹-𝗽𝗲𝗽𝘁𝗶𝗱𝗲 𝗯𝗹𝗲𝗻𝗱 designed to 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝘀𝗸𝗶𝗻 𝗿𝗲𝗰𝗼𝘃𝗲𝗿𝘆 while helping maintain a 𝗰𝗮𝗹𝗺, 𝗯𝗮𝗹𝗮𝗻𝗰𝗲𝗱 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲. 𝗚𝗛𝗞-𝗖𝘂 is recognized in skin science for supporting firmness, texture, and overall skin quality, while 𝗞𝗣𝗩 complements the formula by helping promote a more settled skin environment ideal for acne-prone, redness-prone, or easily reactive skin types. ','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1771151660444-3jjc4zkdkoa.png"]'::jsonb,2,'active','{"category":"cosmetic","srcId":"bdcdf31e-cf9b-40ef-80ef-b37e95007eb0","purity":"99.00","storage":"Store at -20°C"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-hp-glow-precision-pen-v1','hpglow','HPGLOWPRECISIONP','hp-glow-precision-pen-v1','HP Glow Precision Pen V1',139900,'PHP','Upgrade your routine with precision, convenience, and control.

The 𝗛𝗣 𝗚𝗹𝗼𝘄 𝗣𝗿𝗲𝗰𝗶𝘀𝗶𝗼𝗻 𝗣𝗲𝗻 𝗩𝟭 (𝟴𝟬 𝗜𝗨) is designed to simplify your peptide administration while improving accuracy and consistency. Built for both beginners and experienced users, this reusable pen system allows for smooth, controlled dosing without the constant preparation required with traditional syringes.

With its adjustable dial mechanism and 𝘂𝗽 𝘁𝗼 𝟴𝟬 𝗜𝗨 𝗰𝗮𝗽𝗮𝗰𝗶𝘁𝘆, you can easily set your desired units and administer with confidence. The pen-style design offers a more streamlined experience, making it ideal for daily or frequent protocols.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773749027431-ks6bth17rjm.png"]'::jsonb,0,'active','{"category":"all","srcId":"bf161d8d-40e7-4466-acdc-890661422476","purity":"99.00","storage":"Store at -20°C","inclusions":["[1x HP Glow Precision Pen V1","1x Black Precision Pen Case","2x UV Catridges","30x Pen Needles (32g x 6mm/31g x 6m/ 31g x 8mm)]"],"variations":[{"name":"Black","price":1399},{"name":"Coral","price":1399},{"name":"Pink","price":1399}],"variationsMeta":[{"name":"Black","price":1399,"stock":0,"discountPrice":1099},{"name":"Coral","price":1399,"stock":0,"discountPrice":1099.09},{"name":"Pink","price":1399,"stock":0,"discountPrice":1099}]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-pink-hyaluronic-acid-essence','hpglow','PINKHYALURONICAC','pink-hyaluronic-acid-essence','Pink Hyaluronic Acid Essence',48900,'PHP','𝙃𝙮𝙙𝙧𝙖𝙩𝙞𝙣𝙜 • 𝘽𝙧𝙞𝙜𝙝𝙩𝙚𝙣𝙞𝙣𝙜 • 𝙎𝙠𝙞𝙣-𝙍𝙚𝙥𝙖𝙞𝙧 𝙎𝙪𝙥𝙥𝙤𝙧𝙩
𝗣𝗶𝗻𝗸 𝗛𝘆𝗮𝗹𝘂𝗿𝗼𝗻𝗶𝗰 𝗔𝗰𝗶𝗱 𝗘𝘀𝘀𝗲𝗻𝗰𝗲 is a lightweight hydrating essence formulated with Hyaluronic Acid, Tranexamic Acid, PDRN, and Vitamin B12 to 𝗵𝗲𝗹𝗽 𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝗺𝗼𝗶𝘀𝘁𝘂𝗿𝗲 𝗹𝗲𝘃𝗲𝗹𝘀, 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝘀𝗸𝗶𝗻 𝗿𝗲𝗽𝗮𝗶𝗿, 𝗮𝗻𝗱 𝗽𝗿𝗼𝗺𝗼𝘁𝗲 𝗮 𝗯𝗿𝗶𝗴𝗵𝘁𝗲𝗿, 𝗺𝗼𝗿𝗲 𝗲𝘃𝗲𝗻-𝗹𝗼𝗼𝗸𝗶𝗻𝗴 𝗰𝗼𝗺𝗽𝗹𝗲𝘅𝗶𝗼𝗻. Designed for daily topical use, it absorbs quickly and layers seamlessly with your skincare routine. For cosmetic topical use only. Results may vary.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769854156155-x0hg4l25el.png"]'::jsonb,3,'active','{"category":"topicals-and-serums","srcId":"a50aae53-d9c4-4b40-b1fd-9d16f7c45ee0","purity":"99.00","molecularWeight":"3ml","storage":"Store at -20°C","discountEnabled":true,"discountPrice":249}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-glow-sculpt-duo-tirzepatide-30mg-ghk-cu-100mg-free-shipping-','hpglow','GLOWSCULPTDUOTIR-2','glow-sculpt-duo-tirzepatide-30mg-ghk-cu-100mg-free-shipping-','Glow Sculpt Duo (Tirzepatide 30mg & GHK-CU 100mg) - FREE SHIPPING NATIONWIDE',554800,'PHP','The 𝗚𝗹𝗼𝘄 𝗦𝗰𝘂𝗹𝗽𝘁 𝗕𝘂𝗻𝗱𝗹𝗲 combines two peptides commonly used in wellness and metabolic support protocols. 𝗧𝗶𝗿𝘇𝗲𝗽𝗮𝘁𝗶𝗱𝗲 works on GLP-1 and GIP receptors, helping regulate appetite, slow gastric emptying, and support blood sugar control. 𝗚𝗛𝗞-𝗖𝘂 (Copper Peptide) is known for its role in skin repair and regeneration, supporting collagen production, tissue healing, and overall skin health.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1778740277386-n2x6lgeg3n.png"]'::jsonb,4,'active','{"category":"all","srcId":"44650557-730e-4a51-9a35-0c08506cda84","purity":"99.00","storage":"Store at -20°C","featured":true,"freeShipping":true,"discountEnabled":true,"discountPrice":4799}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-ara-290','hpglow','ARA290','ara-290','ARA-290',189900,'PHP','𝗔𝗥𝗔-𝟮𝟵𝟬 (aka Cibinetide) is a synthetic peptide derived from erythropoietin (EPO) designed to activate the innate repair receptor (IRR) and produce 𝗮𝗻𝘁𝗶-𝗶𝗻𝗳𝗹𝗮𝗺𝗺𝗮𝘁𝗼𝗿𝘆, 𝗻𝗲𝘂𝗿𝗼𝗽𝗿𝗼𝘁𝗲𝗰𝘁𝗶𝘃𝗲, 𝗮𝗻𝗱 𝘁𝗶𝘀𝘀𝘂𝗲-𝗿𝗲𝗽𝗮𝗶𝗿 𝗲𝗳𝗳𝗲𝗰𝘁𝘀 without EPO’s red bood-cell-stimulating or pro-thrombotic actions. This peptide has been studied for its potential to 𝗵𝗲𝗹𝗽 𝗿𝗲𝗹𝗶𝗲𝘃𝗲 𝗻𝗲𝘂𝗿𝗼𝗽𝗮𝘁𝗵𝗶𝗰 𝗽𝗮𝗶𝗻, particularly small-fiber neuropathy, while 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝗶𝗻𝗴 𝗻𝗲𝗿𝘃𝗲 𝗿𝗲𝗽𝗮𝗶𝗿 𝗮𝗻𝗱 𝗿𝗲𝗴𝗲𝗻𝗲𝗿𝗮𝘁𝗶𝗼𝗻. It may also help restore immune balance in certain inflammatory and autoimmune conditions.

ARA-290 is also being explored for its role in supporting 𝘁𝗶𝘀𝘀𝘂𝗲 𝗿𝗲𝗰𝗼𝘃𝗲𝗿𝘆 𝗮𝗻𝗱 𝗺𝗲𝘁𝗮𝗯𝗼𝗹𝗶𝗰 𝗵𝗲𝗮𝗹𝘁𝗵, including improvements in lipid and glucose metabolism in individuals with metabolic conditions such as Type 2 diabetes.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773320478037-1gbzrivq38x.png"]'::jsonb,10,'active','{"category":"all","srcId":"41c5a929-b6e9-46e8-8ca8-ef1170ea79fe","purity":"99.00","storage":"Store at -20°C"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-matrixyl-topical-use-only','hpglow','MATRIXYLTOPICALU','matrixyl-topical-use-only','Matrixyl (Topical Use Only)',129900,'PHP','𝗠𝗮𝘁𝗿𝗶𝘅𝘆𝗹 is a well-known peptide used in advanced skincare to help support the skin’s natural collagen production. By encouraging the production of collagen, elastin, and other structural proteins, 𝗶𝘁 𝗵𝗲𝗹𝗽𝘀 𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝘀𝗸𝗶𝗻 𝗳𝗶𝗿𝗺𝗻𝗲𝘀𝘀, 𝗲𝗹𝗮𝘀𝘁𝗶𝗰𝗶𝘁𝘆, 𝗮𝗻𝗱 𝗼𝘃𝗲𝗿𝗮𝗹𝗹 𝘁𝗲𝘅𝘁𝘂𝗿𝗲.

With consistent topical use, Matrixyl may help 𝗿𝗲𝗱𝘂𝗰𝗲 𝘁𝗵𝗲 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗳𝗶𝗻𝗲 𝗹𝗶𝗻𝗲𝘀 𝗮𝗻𝗱 𝘄𝗿𝗶𝗻𝗸𝗹𝗲𝘀 while supporting smoother, more hydrated, and healthier-looking skin. It works with the skin’s natural renewal process, making it a 𝗽𝗼𝗽𝘂𝗹𝗮𝗿 𝗶𝗻𝗴𝗿𝗲𝗱𝗶𝗲𝗻𝘁 𝗶𝗻 𝗺𝗼𝗱𝗲𝗿𝗻 𝗮𝗻𝘁𝗶-𝗮𝗴𝗶𝗻𝗴 𝘀𝗸𝗶𝗻𝗰𝗮𝗿𝗲 𝗳𝗼𝗿𝗺𝘂𝗹𝗮𝘁𝗶𝗼𝗻𝘀.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773319531314-x9dkkb5g82a.png"]'::jsonb,5,'active','{"category":"topicals-and-serums","srcId":"5b705760-c4e3-4a39-93ab-40e7e7af187a","purity":"99.00","featured":true,"discountEnabled":true,"discountPrice":899}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-lumicopper-ghk-cu-topical-set','hpglow','LUMICOPPERGHKCUT','lumicopper-ghk-cu-topical-set','LumiCopper: GHK-CU Topical Set',189900,'PHP','𝗚𝗛𝗞-𝗖𝘂 𝗧𝗼𝗽𝗶𝗰𝗮𝗹 is a next-generation copper peptide recognized in cosmetic science for its ability to 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝗵𝗲𝗮𝗹𝘁𝗵𝗶𝗲𝗿-𝗹𝗼𝗼𝗸𝗶𝗻𝗴, 𝗺𝗼𝗿𝗲 𝗿𝗲𝘀𝗶𝗹𝗶𝗲𝗻𝘁 𝘀𝗸𝗶𝗻. Known for encouraging 𝗰𝗼𝗹𝗹𝗮𝗴𝗲𝗻 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 and 𝗶𝗺𝗽𝗿𝗼𝘃𝗶𝗻𝗴 𝘁𝗵𝗲 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝘀𝗸𝗶𝗻 𝗳𝗶𝗿𝗺𝗻𝗲𝘀𝘀, this peptide helps refine the look of fine lines while promoting a smoother, more refreshed complexion.

Designed to work in synergy with a hyaluronic acid carrier, GHK-Cu helps maintain hydration balance while supporting skin renewal pathways linked to elasticity and overall skin quality. Over time, skin appears more supple, refined, and visibly revitalized.

FOR TOPICAL USE ONLY.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1770964880430-lutuoq1av9s.png"]'::jsonb,4,'active','{"category":"topicals-and-serums","srcId":"9af17675-838b-4c51-b808-ee67cd8124b6","purity":"99.00","storage":"Store at -20°C","freeShipping":true,"inclusions":["[Torriden Dive In Low Molecular Hyaluronic Acid Serum 50ml","GHK-CU Topical 1g","2pcs Saline Water 5ml","2pcs 3cc Syringe","10 Alcohol Pads","1/8tsp Measuring Spoon","Small Ceramic Bowl","Small Silicone Mixer]"]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-tirzepatide-60mg-tirzepatide-10mg','hpglow','TIRZEPATIDE60MGT','tirzepatide-60mg-tirzepatide-10mg','[𝗔𝗣𝗥𝗜𝗟 𝗘𝗫𝗖𝗟𝗨𝗦𝗜𝗩𝗘] TIRZEPATIDE 60mg + Tirzepatide 10mg',569900,'PHP','Tirzepatide 60mg with FREE Tirzepatide 10mg Kit. PROMO PERIOD: Until supplies last.
','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1774846414587-qubn5wcg.png"]'::jsonb,0,'draft','{"category":"all","srcId":"1b30314e-6eb2-45e8-b04a-a334ee03c66e","purity":"99.00","storage":"Store at -20°C","featured":true,"freeShipping":true}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-5-amino-1mq','hpglow','5AMINO1MQ','5-amino-1mq','5-Amino-1MQ',198900,'PHP','𝟱-𝗔𝗺𝗶𝗻𝗼-𝟭𝗠𝗤 is a metabolic-support compound designed to 𝗵𝗲𝗹𝗽 𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝗯𝗼𝗱𝘆 𝗰𝗼𝗺𝗽𝗼𝘀𝗶𝘁𝗶𝗼𝗻 𝗮𝗻𝗱 𝗲𝗻𝗲𝗿𝗴𝘆 𝗺𝗲𝘁𝗮𝗯𝗼𝗹𝗶𝘀𝗺. By inhibiting the NNMT enzyme, it helps preserve NAD⁺ levels, supporting mitochondrial function, fat metabolism, and cellular energy production.

This compound is widely explored for its potential to 𝗽𝗿𝗼𝗺𝗼𝘁𝗲 𝗳𝗮𝘁 𝗹𝗼𝘀𝘀 𝘄𝗵𝗶𝗹𝗲 𝗵𝗲𝗹𝗽𝗶𝗻𝗴 𝗽𝗿𝗲𝘀𝗲𝗿𝘃𝗲 𝗹𝗲𝗮𝗻 𝗺𝘂𝘀𝗰𝗹𝗲 𝗺𝗮𝘀𝘀. It may also support insulin sensitivity, metabolic efficiency, and overall cellular health.

Because of its role in improving metabolic activity and mitochondrial function, 𝟱-𝗔𝗺𝗶𝗻𝗼-𝟭𝗠𝗤 𝗵𝗮𝘀 𝗴𝗮𝗶𝗻𝗲𝗱 𝗮𝘁𝘁𝗲𝗻𝘁𝗶𝗼𝗻 𝗶𝗻 𝗳𝗮𝘁 𝗹𝗼𝘀𝘀, 𝗺𝗲𝘁𝗮𝗯𝗼𝗹𝗶𝗰 𝗵𝗲𝗮𝗹𝘁𝗵, 𝗮𝗻𝗱 𝗹𝗼𝗻𝗴𝗲𝘃𝗶𝘁𝘆-𝗳𝗼𝗰𝘂𝘀𝗲𝗱 𝗽𝗿𝗼𝘁𝗼𝗰𝗼𝗹𝘀.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773320940821-8d34xwq3dvk.png"]'::jsonb,1,'active','{"category":"all","srcId":"75f4bd87-0a39-45a3-b5e9-ae2353225576","purity":"99.00","storage":"Store at -20°C"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-smooth8-reset-snap-8-topical-set','hpglow','SMOOTH8RESETSNAP','smooth8-reset-snap-8-topical-set','Smooth8 Reset (Snap-8 Topical Set)',179900,'PHP','“𝗕𝗼𝘁𝗼𝘅-𝗜𝗻𝘀𝗽𝗶𝗿𝗲𝗱 𝗥𝗲𝘀𝘂𝗹𝘁𝘀. 𝗡𝗼 𝗡𝗲𝗲𝗱𝗹𝗲𝘀.”

Meet 𝗦𝗡𝗔𝗣-𝟴, the advanced neuro-peptide often called “𝗕𝗼𝘁𝗼𝘅 𝗶𝗻 𝗮 𝗕𝗼𝘁𝘁𝗹𝗲” in the skincare world. Designed for topical use, this next-generation peptide helps 𝘀𝗼𝗳𝘁𝗲𝗻 𝘁𝗵𝗲 𝗹𝗼𝗼𝗸 𝗼𝗳 𝗲𝘅𝗽𝗿𝗲𝘀𝘀𝗶𝗼𝗻 𝗹𝗶𝗻𝗲𝘀 by targeting the same surface pathways associated with repetitive facial movements — without injections, downtime, or stiffness. SNAP-8 is a refined version of Argireline, formulated to 𝗵𝗲𝗹𝗽 𝘃𝗶𝘀𝗶𝗯𝗹𝘆 𝘀𝗺𝗼𝗼𝘁𝗵 𝗳𝗶𝗻𝗲 𝗹𝗶𝗻𝗲𝘀 𝗮𝗻𝗱 𝘄𝗿𝗶𝗻𝗸𝗹𝗲𝘀 over time. When used consistently, it supports a more relaxed, refreshed, and youthful appearance, especially in high-movement areas like the forehead, crow’s feet, and smile lines.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1770965100162-tnvb0tujk6i.png"]'::jsonb,2,'active','{"category":"topicals-and-serums","srcId":"0eeef65d-051a-467c-ac3b-9c60014eab15","purity":"99.00","freeShipping":true,"inclusions":["[𝗜𝗻𝗰𝗹𝘂𝘀𝗶𝗼𝗻𝘀:","Good Molecules Hyaluronic Acid Serum","Snap-8","Phosphate Buffered Saline","2pcs 3ml Disposable Syringe","10pcs Alcohol Pads]"]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-collagen-skinbooster','hpglow','COLLAGENSKINBOOS','collagen-skinbooster','Collagen Skinbooster',59900,'PHP','𝗖𝗼𝗹𝗹𝗮𝗴𝗲𝗻 𝗦𝗸𝗶𝗻𝗯𝗼𝗼𝘀𝘁𝗲𝗿 is a topical skincare concentrate 𝗳𝗼𝗿𝗺𝘂𝗹𝗮𝘁𝗲𝗱 𝘄𝗶𝘁𝗵 𝗧𝘆𝗽𝗲 𝗜 𝗖𝗼𝗹𝗹𝗮𝗴𝗲𝗻 𝗣𝗿𝗼𝘁𝗲𝗶𝗻 to help support skin hydration, smoothness, and a more supple-looking complexion. Designed to work at the surface level of the skin, this skinbooster 𝗵𝗲𝗹𝗽𝘀 𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝘁𝗵𝗲 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗱𝗿𝘆𝗻𝗲𝘀𝘀, 𝗳𝗶𝗻𝗲 𝘁𝗲𝘅𝘁𝘂𝗿𝗲, 𝗮𝗻𝗱 𝗹𝗼𝘀𝘀 𝗼𝗳 𝗳𝗶𝗿𝗺𝗻𝗲𝘀𝘀 caused by environmental stress and natural ageing. With regular use, skin appears smoother, more hydrated, and refreshed. For cosmetic topical use only. Results may vary.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769853970512-shtqgkk2lzj.png"]'::jsonb,10,'active','{"category":"topicals-and-serums","srcId":"ef93416a-2343-46b4-8b77-5d5cd09b0e4c","purity":"99.00","molecularWeight":"3ml","storage":"Store at -20°C","discountEnabled":true,"discountPrice":249}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-aqualyx','hpglow','AQUALYX','aqualyx','Aqualyx ',350000,'PHP','Aqualyx (Cosmetic Grade) is a premium, non-surgical fat-dissolving solution designed to precisely target stubborn localized fat. Favoured by leading aesthetic professionals, it delivers refined contouring and visibly smoother results without surgery. Targets stubborn, localized fat, Non-surgical body contouring solution, Precision treatment for refined shaping, Gradual, natural-looking results, Trusted by aesthetic professionals worldwide. Common treatment areas include the chin, jawline, abdomen, flanks, thighs, and knees.

For professional use only. Aqualyx is not a weight-loss treatment but a premium solution for enhancing body definition and contour.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766627551065-81cjee8o57m.png"]'::jsonb,2,'active','{"category":"face-body-contouring","srcId":"17a1fea2-b131-48b9-9010-c0e4452ab560","purity":"99.00","storage":"Store at -20°C","inclusions":["[Sungshim 31g x 8mm Insulin Syringe: 10pcs","Transparent vial case","Tape Measure","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"]}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-pure-pdrn-serum-form-10-days-use','hpglow','PUREPDRNSERUMFOR','pure-pdrn-serum-form-10-days-use','Pure PDRN Serum Form 10 days use',118900,'PHP','𝙎𝙠𝙞𝙣 𝙍𝙚𝙥𝙖𝙞𝙧 • 𝘽𝙖𝙧𝙧𝙞𝙚𝙧 𝙎𝙪𝙥𝙥𝙤𝙧𝙩 • 𝙃𝙮𝙙𝙧𝙖𝙩𝙞𝙤𝙣 𝘽𝙤𝙤𝙨𝙩
𝗣𝘂𝗿𝗲 𝗣𝗗𝗥𝗡 𝗦𝗲𝗿𝘂𝗺 𝗙𝗼𝗿𝗺 is a lightweight topical serum formulated with PDRN (Polydeoxyribonucleotide) to 𝗵𝗲𝗹𝗽 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝘀𝗸𝗶𝗻 𝗿𝗲𝗽𝗮𝗶𝗿, 𝗵𝘆𝗱𝗿𝗮𝘁𝗶𝗼𝗻, 𝗮𝗻𝗱 𝗼𝘃𝗲𝗿𝗮𝗹𝗹 𝘀𝗸𝗶𝗻 𝗿𝗲𝘀𝗶𝗹𝗶𝗲𝗻𝗰𝗲. Designed for surface-level skin care, this serum is ideal for skin that appears stressed, dull, or compromised by environmental exposure and daily wear. 𝗣𝗗𝗥𝗡 𝗶𝘀 𝗸𝗻𝗼𝘄𝗻 𝗳𝗼𝗿 𝗶𝘁𝘀 𝗿𝗼𝗹𝗲 𝗶𝗻 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝗶𝗻𝗴 𝘀𝗸𝗶𝗻 𝗿𝗲𝗻𝗲𝘄𝗮𝗹 𝗮𝗻𝗱 𝗿𝗲𝗰𝗼𝘃𝗲𝗿𝘆 𝗯𝘆 𝗵𝗲𝗹𝗽𝗶𝗻𝗴 𝗶𝗺𝗽𝗿𝗼𝘃𝗲 𝘁𝗵𝗲 𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝘁𝗲𝘅𝘁𝘂𝗿𝗲 𝗮𝗻𝗱 𝗲𝗹𝗮𝘀𝘁𝗶𝗰𝗶𝘁𝘆. When used topically, it helps reinforce the skin barrier, support moisture retention, and promote a healthier-looking complexion over time. For cosmetic topical use only. Results may vary.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769856089796-9zyw7v0lddk.png"]'::jsonb,1,'active','{"category":"topicals-and-serums","srcId":"56d5fbae-f0fa-4f19-9662-826de620fb7c","purity":"99.00"}'::jsonb);
INSERT INTO products (id,"tenantId",sku,slug,name,"priceCents",currency,description,images,stock,status,metadata) VALUES ('hpglow-aod-9604','hpglow','AOD9604','aod-9604','AOD-9604',209900,'PHP','[SENSITIVE PEPTIDE. HARD TO RECONSTITUTE IF NOT RESEARCHED PROPERLY. NO REFUNDS FOR GELLING]. 𝗔𝗢𝗗-𝟵𝟲𝟬𝟰 𝗶𝘀 𝗮𝗻 𝗮𝗻𝘁𝗶-𝗼𝗯𝗲𝘀𝗶𝘁𝘆 peptide designed to 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝘁𝗮𝗿𝗴𝗲𝘁𝗲𝗱 𝗳𝗮𝘁 𝗿𝗲𝗱𝘂𝗰𝘁𝗶𝗼𝗻, with a 𝗳𝗼𝗰𝘂𝘀 𝗼𝗻 𝘃𝗶𝘀𝗰𝗲𝗿𝗮𝗹 𝗮𝗻𝗱 𝘀𝘁𝘂𝗯𝗯𝗼𝗿𝗻 𝗳𝗮𝘁 𝗱𝗲𝗽𝗼𝘀𝗶𝘁𝘀. It helps stimulate fat metabolism while supporting lean muscle preservation, making it ideal for individuals looking to improve body composition and overall fat management. Research Grade Peptide.','["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766624718821-gpy8uppa7t8.png"]'::jsonb,3,'active','{"category":"research","srcId":"75db65d1-8b53-44d3-a638-0e5dc30dfa64","purity":"99.00","storage":"Store at -20°C","inclusions":["[Syringe for Reconstitution","Sungshim 31g x 8mm Insulin Syringe: 10pcs","10pcs (100mg) and 20pcs (500mg) Alcohol Pads","NAOD-9604+ Printed Guide","Transparent vial case and vial cap","FREE Black Peptide Vial Case 3ml","Peptide Injection and Inventory Spreadsheet tracker","ㅤㅤㅤㅤㅤㅤ","𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?","Certificate of Analysis (COA) available","Viber Community (290+ members)","Doctor onboard (you can avail online consultations with her for as low as ₱400)","Community perks (ebooks, guides, monthly giveaways)","Freebies beyond Tirz, you’ll love!]"],"variations":[{"name":"5mg","price":2099}],"variationsMeta":[{"name":"5mg","price":2099,"stock":4,"discountPrice":1599}]}'::jsonb);

COMMIT;

-- Summary: 42 products (36 active / 6 draft), 31 variations, 6 COA reports, 5 payment methods. Orders + vouchers excluded.
