-- HP GLOW -> tenant 'hpglow' catalog seed for the multi-tenant peptide SaaS
-- Inserts into EXISTING tables: tenants, branding, tenant_settings, products.
-- Currency: PHP (peso). priceCents = pesos*100. metadata.variations price = MAJOR units.
-- Idempotent: ON CONFLICT DO NOTHING on every unique target. Safe to re-run.
-- planId is subqueried from plans (key='ecommerce') -- change the key if needed.

BEGIN;

-- 1) Tenant
INSERT INTO tenants (id, name, slug, status, "planId")
VALUES ('hpglow', 'HP GLOW', 'hpglow', 'active',
        (SELECT id FROM plans WHERE key = 'ecommerce' LIMIT 1))
ON CONFLICT (slug) DO NOTHING;

-- 2) Branding (categories + payment methods live in config; rest minimal, edit in admin)
INSERT INTO branding (id, "tenantId", "logoUrl", "themeId", colors, fonts, config)
VALUES ('hpglow-branding', 'hpglow', NULL, 'default',
        '{"primary":"#000000","background":"#ffffff"}'::jsonb,
        '{"heading":"Inter","body":"Inter"}'::jsonb,
        '{"currency": "₱", "categories": [{"id": "all", "label": "All Products"}, {"id": "research", "label": "Weight Management"}, {"id": "cosmetic", "label": "Beauty & Anti-Aging"}, {"id": "wellness", "label": "Wellness & Vitality"}, {"id": "supplies", "label": "Supplies & Accessories"}, {"id": "face-body-contouring", "label": "Face & Body Contouring"}, {"id": "topicals-and-serums", "label": "Topicals and Serums"}], "paymentMethods": [{"id": "gcash", "name": "GCash", "account": "HP GLOW", "number": "09XX XXX XXXX", "qrImage": "https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1764588827991-pfuhkf9k69.jpeg", "order": 1, "active": true}, {"id": "gcash-2", "name": "Gcash 2", "account": "HP GLOW ", "number": "09XXXXXXXXX", "qrImage": "https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1764589014648-xigyp23nv8a.jpeg", "order": 2, "active": false}, {"id": "bpi", "name": "BPI", "account": "HP GLOW", "number": "n/a", "qrImage": "https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1764589095410-7eyd6fnwg7.jpeg", "order": 3, "active": true}, {"id": "gotyme", "name": "GoTyme Bank", "account": "HP GLOW", "number": "n/a", "qrImage": "https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1764589167539-c199joy8ise.jpeg", "order": 4, "active": true}, {"id": "credit-card-qrph", "name": "Credit Card (QRPH)", "account": "High Point Digitals", "number": "123****", "qrImage": "https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1777632324923-zh0icxn78tr.jpg", "order": 5, "active": true}]}'::jsonb)
ON CONFLICT ("tenantId") DO NOTHING;

-- 3) Store settings
INSERT INTO tenant_settings (id, "tenantId", "storeName", "supportEmail", currency)
VALUES ('hpglow-settings', 'hpglow', 'HP GLOW', NULL, 'PHP')
ON CONFLICT ("tenantId") DO NOTHING;

-- 4) Products (42 rows)
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-001', 'hpglow', 'PT-141', 'pt-141', 'PT-141', 149900, 'PHP', 100, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766626600078-1hpeuvnu5ovi.png"]'::jsonb, '{"category": "Wellness & Vitality", "currencySymbol": "₱", "purity": "99%", "cas": "189691-06-3", "molecularWeight": "1025.19 g/mol", "storage": "Store at -20°C. Reconstituted solution at 2-8°C for up to 30 days.", "sequence": "Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-OH", "variations": [{"name": "10mg", "price": 1499}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-002', 'hpglow', 'TIRZEPATIDE', 'tirzepatide', 'Tirzepatide', 249900, 'PHP', 100, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766432919623-sjzdawaxlo7.png"]'::jsonb, '{"category": "Weight Management", "currencySymbol": "₱", "featured": true, "purity": "99.81%", "cas": "2026788-19-2", "molecularWeight": "31.23mg", "storage": "Store at -20°C for long-term storage. Reconstituted solution should be stored at 2-8°C.", "sequence": "Proprietary", "isSet": true, "inclusions": [{"name": "Syringe for Reconstitution", "qty": 1}, {"name": "Sungshim 31g x 8mm Insulin Syringe: 6pcs (15mg and 20mg), 7pcs (30mg), and 10pcs (60mg)", "qty": 1}, {"name": "Tirzepatide Printed Guide", "qty": 1}, {"name": "Transparent vial case and vial cap", "qty": 1}, {"name": "FREE Black Peptide Vial Case 3ml for 60mg", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Certificate of Analysis (COA) available", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}], "variations": [{"name": "30mg", "price": 3499}, {"name": "15mg", "price": 2499}, {"name": "20mg", "price": 2899}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-003', 'hpglow', 'RETATRUTIDE', 'retatrutide', 'Retatrutide', 349900, 'PHP', 0, 'draft', '[]'::jsonb, '{"category": "Weight Management", "currencySymbol": "₱", "featured": true, "purity": "99.5%", "storage": "Store at -20°C", "variations": [{"name": "20mg", "price": 3499}, {"name": "30mg", "price": 4299}, {"name": "15mg", "price": 3499}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-004', 'hpglow', 'AOD-9604', 'aod-9604', 'AOD-9604', 209900, 'PHP', 3, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766624718821-gpy8uppa7t8.png"]'::jsonb, '{"category": "Weight Management", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "isSet": true, "inclusions": [{"name": "Syringe for Reconstitution", "qty": 1}, {"name": "Sungshim 31g x 8mm Insulin Syringe: 10pcs", "qty": 1}, {"name": "10pcs (100mg) and 20pcs (500mg) Alcohol Pads", "qty": 1}, {"name": "NAOD-9604+ Printed Guide", "qty": 1}, {"name": "Transparent vial case and vial cap", "qty": 1}, {"name": "FREE Black Peptide Vial Case 3ml", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Certificate of Analysis (COA) available", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}], "variations": [{"name": "5mg", "price": 2099}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-005', 'hpglow', 'GHK-CU', 'ghk-cu', 'GHK-CU', 119900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766434820735-29nxomdz57b.png"]'::jsonb, '{"category": "Beauty & Anti-Aging", "currencySymbol": "₱", "featured": true, "purity": "99%", "storage": "Store at -20°C", "isSet": true, "inclusions": [{"name": "Syringe for Reconstitution", "qty": 1}, {"name": "Sungshim 31g x 8mm Insulin Syringe: 10pcs (50mg) and 20pcs (100mg)", "qty": 1}, {"name": "10pcs Alcohol Pads", "qty": 1}, {"name": "GHK-CU Printed Guide", "qty": 1}, {"name": "Transparent vial case and vial cap", "qty": 1}, {"name": "FREE Black Peptide Vial Case", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Certificate of Analysis (COA) available", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}], "variations": [{"name": "100mg", "price": 1850}, {"name": "50mg", "price": 1199}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-006', 'hpglow', 'GLUTATHIONE', 'glutathione', 'Glutathione', 149900, 'PHP', 28, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766626085984-goh4gkej4c6.png"]'::jsonb, '{"category": "Beauty & Anti-Aging", "currencySymbol": "₱", "featured": true, "purity": "99%", "storage": "Store at -20°C", "discountEnabled": true, "discountPrice": 999.0, "isSet": true, "inclusions": [{"name": "Syringe for Reconstitution - 1pc", "qty": 1}, {"name": "Terumo Insulin Syringe 30g x 3/8\" - 7pcs", "qty": 1}, {"name": "10pcs Alcohol Pads", "qty": 1}, {"name": "Glutathione Printed Guide", "qty": 1}, {"name": "Vial cap", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}], "variations": [{"name": "1500mg", "price": 1499}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-007', 'hpglow', 'CAGRILINTIDE', 'cagrilintide', 'Cagrilintide', 179900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766624826888-38ofy94ib5q.png"]'::jsonb, '{"category": "Weight Management", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "variations": [{"name": "5mg", "price": 1799}, {"name": "10mg", "price": 2299}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-008', 'hpglow', 'SELANK', 'selank', 'Selank', 149900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766627072044-wwgdoy7bdm.png"]'::jsonb, '{"category": "Wellness & Vitality", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "variations": [{"name": "10mg", "price": 1799}, {"name": "5mg", "price": 1499}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-009', 'hpglow', 'SEMAX', 'semax', 'Semax', 139900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766626990312-uf80l2sam4b.png"]'::jsonb, '{"category": "Wellness & Vitality", "currencySymbol": "₱", "purity": "98.8%", "storage": "Store at -20°C", "isSet": true, "inclusions": [{"name": "Syringe for Reconstitution", "qty": 1}, {"name": "Sungshim 31g x 8mm Insulin Syringe: 10pcs (5mg) and 16pcs (10mg)", "qty": 1}, {"name": "10pcs (100mg) and 20pcs (500mg) Alcohol Pads", "qty": 1}, {"name": "SEMAX+ Printed Guide", "qty": 1}, {"name": "Transparent vial case and vial cap", "qty": 1}, {"name": "FREE Black Peptide Vial Case 3ml", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}], "variations": [{"name": "5mg", "price": 1399}, {"name": "10mg", "price": 1699}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-010', 'hpglow', 'GLOW-BPC-157-GHK-CU-TB500', 'glow-bpc-157-ghk-cu-tb500', 'GLOW (BPC-157, GHK-CU, TB500)', 289900, 'PHP', 0, 'draft', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766434887907-if0ggjkava.png"]'::jsonb, '{"category": "Wellness & Vitality", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "variations": [{"name": "70mg", "price": 2899}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-011', 'hpglow', 'LIPO-C-WITH-B12', 'lipo-c-with-b12', 'Lipo-C with B12', 169900, 'PHP', 1, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766627187213-y7ueqhpcmu9.png"]'::jsonb, '{"category": "Weight Management", "currencySymbol": "₱", "purity": "99%", "storage": "Store at room temperature", "variations": [{"name": "10ml", "price": 1699}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-012', 'hpglow', 'LEMON-BOTTLE', 'lemon-bottle', 'Lemon Bottle', 129900, 'PHP', 17, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766627165597-jod4dr4fts.png"]'::jsonb, '{"category": "Face & Body Contouring", "currencySymbol": "₱", "featured": true, "purity": "99%", "storage": "Store at room temperature", "isSet": true, "inclusions": [{"name": "10pcs Sungshim 31g x 8mm Insulin Syringe", "qty": 1}, {"name": "Transparent vial case", "qty": 1}, {"name": "Vial Opener", "qty": 1}, {"name": "Skin Marker and Ruler White", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Certificate of Analysis (COA) available for tirz", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}], "variations": [{"name": "10ml", "price": 1299}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-013', 'hpglow', 'NAD', 'nad', 'NAD+', 129900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766433789611-20ii0sd19cb.png"]'::jsonb, '{"category": "Wellness & Vitality", "currencySymbol": "₱", "featured": true, "purity": "99.5%", "storage": "Store at -20°C", "isSet": true, "inclusions": [{"name": "Syringe for Reconstitution", "qty": 1}, {"name": "Sungshim 31g x 8mm Insulin Syringe: 10pcs (100mg) and 20pcs (500mg) Alcohol Pads", "qty": 1}, {"name": "NAD+ Printed Guide", "qty": 1}, {"name": "Transparent vial case and vial cap", "qty": 1}, {"name": "FREE Black Peptide Vial Case 10ml", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Certificate of Analysis (COA) available", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}], "variations": [{"name": "100mg", "price": 1299}, {"name": "500mg", "price": 2199}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-014', 'hpglow', 'KISSPEPTIN', 'kisspeptin', 'Kisspeptin', 169900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766625201103-no41bb27ofi.png"]'::jsonb, '{"category": "Wellness & Vitality", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "variations": [{"name": "10mg", "price": 2399}, {"name": "5mg", "price": 1699}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-015', 'hpglow', 'RETATRUTIDE-30MG-FREE-SHIPPING-NATIONWIDE', 'retatrutide-30mg-free-shipping-nationwide', 'Retatrutide 30mg (Free Shipping Nationwide)', 429900, 'PHP', 1, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766433855825-399qkyckp54.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "discountEnabled": true, "discountPrice": 3899.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-016', 'hpglow', 'SUNGSHIM-31G-X-8MM-INSULIN-SYRINGE', 'sungshim-31g-x-8mm-insulin-syringe', 'Sungshim 31g x 8mm Insulin Syringe', 1200, 'PHP', 26, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766626711690-imzqkb5w9ps.jpg"]'::jsonb, '{"category": "Supplies & Accessories", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-017', 'hpglow', 'AQUALYX', 'aqualyx', 'Aqualyx ', 350000, 'PHP', 2, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1766627551065-81cjee8o57m.png"]'::jsonb, '{"category": "Face & Body Contouring", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "isSet": true, "inclusions": [{"name": "Sungshim 31g x 8mm Insulin Syringe: 10pcs", "qty": 1}, {"name": "Transparent vial case", "qty": 1}, {"name": "Tape Measure", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-018', 'hpglow', 'THE-GLOW-SLIM-DUO-TIRZEPATIDE-60MG-GHK-CU-50MG-SET', 'the-glow-slim-duo-tirzepatide-60mg-ghk-cu-50mg-set', 'THE GLOW + SLIM DUO (Tirzepatide 60mg & GHK-CU 50mg Set)', 569900, 'PHP', 0, 'draft', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1768454653873-6q70upkv1o9.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "isSet": true, "inclusions": [{"name": "Syringe for Reconstitution", "qty": 1}, {"name": "Sungshim 31g x 8mm Insulin Syringe: 10pcs (Tirze 60mg) and 10pcs (GHK-CU 50mg)", "qty": 1}, {"name": "Tirzepatide & GHK-CU Printed Guides", "qty": 1}, {"name": "Transparent vial case and vial cap", "qty": 1}, {"name": "FREE Black Peptide Vial Case 3ml and 10ml", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Certificate of Analysis (COA) available", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-019', 'hpglow', 'THYMOSIN-ALPHA-1', 'thymosin-alpha-1', 'Thymosin Alpha-1', 109900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769043180174-97i3s7fv2jc.png"]'::jsonb, '{"category": "Wellness & Vitality", "currencySymbol": "₱", "purity": "99%", "variations": [{"name": "5mg", "price": 1099}, {"name": "10mg", "price": 2099}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-020', 'hpglow', 'TESAMORELIN', 'tesamorelin', 'Tesamorelin', 179900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769338290260-qx8k5tbrsy.jpeg"]'::jsonb, '{"category": "Weight Management", "currencySymbol": "₱", "purity": "99%", "storage": "Store at 2°C to 8°C once reconstituted", "isSet": true, "inclusions": [{"name": "𝗜𝗻𝗰𝗹𝘂𝘀𝗶𝗼𝗻𝘀:", "qty": 1}, {"name": "•  Syringe for Reconstitution", "qty": 1}, {"name": "•  10pcs Sungshim 31g x 8mm Insulin Syringe", "qty": 1}, {"name": "•  10pcs Alcohol Pads", "qty": 1}, {"name": "•  Tirzepatide Printed Guide", "qty": 1}, {"name": "•  Transparent vial case and vial cap", "qty": 1}, {"name": "•  Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "✅ Certificate of Analysis (COA) available", "qty": 1}, {"name": "✅ Viber Community (290+ members)", "qty": 1}, {"name": "✅ Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "✅ Community perks", "qty": 1}, {"name": "✅ Freebies beyond Tirz, you’ll love!", "qty": 1}], "variations": [{"name": "5mg", "price": 1799}, {"name": "10mg", "price": 2399}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-021', 'hpglow', 'SNAP-8-TOPICAL-USE-ONLY', 'snap-8-topical-use-only', 'Snap-8 (Topical Use Only)', 99900, 'PHP', -2, 'draft', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769338726217-aa09yk2itk.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C (unreconstituted)"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-022', 'hpglow', 'GHK-CU-COSMETIC-GRADE-TOPICAL-USE-ONLY', 'ghk-cu-cosmetic-grade-topical-use-only', 'GHK-CU Cosmetic Grade (Topical Use Only)', 84900, 'PHP', 5, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769339253093-7eaq5so1ez6.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "discountEnabled": true, "discountPrice": 701.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-023', 'hpglow', 'AHK-CU-COSMETIC-GRADE-TOPICAL-USE-ONLY', 'ahk-cu-cosmetic-grade-topical-use-only', 'AHK-CU Cosmetic Grade (Topical Use Only)', 128000, 'PHP', 4, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769339818484-ijw11jgjb2.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "discountEnabled": true, "discountPrice": 699.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-024', 'hpglow', 'PDRN-COSMETIC-GRADE-TOPICAL-USE-ONLY', 'pdrn-cosmetic-grade-topical-use-only', 'PDRN Cosmetic Grade (Topical Use Only)', 179900, 'PHP', 1, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769340207120-dt4u1iya59p.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-025', 'hpglow', 'GLOW-BPC-157-GHK-CU-TB500-70MG', 'glow-bpc-157-ghk-cu-tb500-70mg', 'Glow (BPC-157, GHK-CU, TB500) 70mg', 289900, 'PHP', 3, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769340494172-m30sjy604k8.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "molecularWeight": "70mg", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-026', 'hpglow', 'TIRZEPATIDE-60MG-FREE-SHIPPING-NATIONWIDE', 'tirzepatide-60mg-free-shipping-nationwide', 'Tirzepatide 60mg (Free Shipping Nationwide)', 569900, 'PHP', 1, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769416025786-n55pc3ebp1m.png"]'::jsonb, '{"category": "Weight Management", "currencySymbol": "₱", "purity": "99.81%", "cas": "2026788-19-2", "molecularWeight": "31.23mg", "storage": "Store at -20°C for long-term storage. Reconstituted solution should be stored at 2-8°C.", "isSet": true, "inclusions": [{"name": "Syringe for Reconstitution", "qty": 1}, {"name": "Sungshim 31g x 8mm Insulin Syringe: 10pcs (60mg)", "qty": 1}, {"name": "Tirzepatide Printed Guide", "qty": 1}, {"name": "Transparent vial case and vial cap", "qty": 1}, {"name": "FREE Black Peptide Vial Case 3ml for 60mg", "qty": 1}, {"name": "Peptide Injection and Inventory Spreadsheet tracker", "qty": 1}, {"name": " ㅤㅤㅤㅤㅤㅤ", "qty": 1}, {"name": "𝗪𝗛𝗬 𝗖𝗛𝗢𝗢𝗦𝗘 𝗛𝗣 𝗚𝗟𝗢𝗪?", "qty": 1}, {"name": "Certificate of Analysis (COA) available", "qty": 1}, {"name": "Viber Community (290+ members)", "qty": 1}, {"name": "Doctor onboard (you can avail online consultations with her for as low as ₱400)", "qty": 1}, {"name": "Community perks (ebooks, guides, monthly giveaways)", "qty": 1}, {"name": "Freebies beyond Tirz, you’ll love!", "qty": 1}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-027', 'hpglow', 'WHITENING-SPOT-FADING-SKINBOOSTER', 'whitening-spot-fading-skinbooster', 'Whitening & Spot-Fading Skinbooster', 48900, 'PHP', 4, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769853744472-abbk1ooe7go.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "molecularWeight": "3ml", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-028', 'hpglow', 'COLLAGEN-SKINBOOSTER', 'collagen-skinbooster', 'Collagen Skinbooster', 59900, 'PHP', 10, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769853970512-shtqgkk2lzj.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "molecularWeight": "3ml", "storage": "Store at -20°C", "discountEnabled": true, "discountPrice": 249.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-029', 'hpglow', 'PINK-HYALURONIC-ACID-ESSENCE', 'pink-hyaluronic-acid-essence', 'Pink Hyaluronic Acid Essence', 48900, 'PHP', 3, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769854156155-x0hg4l25el.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "molecularWeight": "3ml", "storage": "Store at -20°C", "discountEnabled": true, "discountPrice": 249.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-030', 'hpglow', 'PURE-PDRN-SERUM-FORM-10-DAYS-USE', 'pure-pdrn-serum-form-10-days-use', 'Pure PDRN Serum Form 10 days use', 118900, 'PHP', 1, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1769856089796-9zyw7v0lddk.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-031', 'hpglow', 'SMOOTH8-RESET-SNAP-8-TOPICAL-SET', 'smooth8-reset-snap-8-topical-set', 'Smooth8 Reset (Snap-8 Topical Set)', 179900, 'PHP', 2, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1770965100162-tnvb0tujk6i.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "isSet": true, "inclusions": [{"name": "𝗜𝗻𝗰𝗹𝘂𝘀𝗶𝗼𝗻𝘀:", "qty": 1}, {"name": "Good Molecules Hyaluronic Acid Serum", "qty": 1}, {"name": "Snap-8", "qty": 1}, {"name": "Phosphate Buffered Saline", "qty": 1}, {"name": "2pcs 3ml Disposable Syringe", "qty": 1}, {"name": "10pcs Alcohol Pads", "qty": 1}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-032', 'hpglow', 'LUMICOPPER-GHK-CU-TOPICAL-SET', 'lumicopper-ghk-cu-topical-set', 'LumiCopper: GHK-CU Topical Set', 189900, 'PHP', 4, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1770964880430-lutuoq1av9s.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "isSet": true, "inclusions": [{"name": "Torriden Dive In Low Molecular Hyaluronic Acid Serum 50ml", "qty": 1}, {"name": "GHK-CU Topical 1g", "qty": 1}, {"name": "2pcs Saline Water 5ml", "qty": 1}, {"name": "2pcs 3cc Syringe", "qty": 1}, {"name": "10 Alcohol Pads", "qty": 1}, {"name": "1/8tsp Measuring Spoon", "qty": 1}, {"name": "Small Ceramic Bowl", "qty": 1}, {"name": "Small Silicone Mixer", "qty": 1}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-033', 'hpglow', 'GHK-CU-KPV-BLEND-60MG', 'ghk-cu-kpv-blend-60mg', 'GHK-CU + KPV Blend 60mg', 189900, 'PHP', 2, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1771151660444-3jjc4zkdkoa.png"]'::jsonb, '{"category": "Beauty & Anti-Aging", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-034', 'hpglow', 'BIRTHDAY-FLASH-BUNDLE-SALE', 'birthday-flash-bundle-sale', 'BIRTHDAY FLASH BUNDLE SALE!', 569900, 'PHP', 0, 'draft', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1772089755682-m07i3zrwgl.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-035', 'hpglow', 'MATRIXYL-TOPICAL-USE-ONLY', 'matrixyl-topical-use-only', 'Matrixyl (Topical Use Only)', 129900, 'PHP', 5, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773319531314-x9dkkb5g82a.png"]'::jsonb, '{"category": "Topicals and Serums", "currencySymbol": "₱", "featured": true, "purity": "99%", "discountEnabled": true, "discountPrice": 899.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-036', 'hpglow', 'ARA-290', 'ara-290', 'ARA-290', 189900, 'PHP', 10, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773320478037-1gbzrivq38x.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-037', 'hpglow', '5-AMINO-1MQ', '5-amino-1mq', '5-Amino-1MQ', 198900, 'PHP', 1, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773320940821-8d34xwq3dvk.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-038', 'hpglow', 'GLOW-SCULPT-DUO-TIRZEPATIDE-15MG-GHK-CU-50MG', 'glow-sculpt-duo-tirzepatide-15mg-ghk-cu-50mg', 'Glow Sculpt Duo (Tirzepatide 15mg & GHK-CU 50mg)', 369800, 'PHP', 5, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773322270052-t3r5ijpk8k.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "discountEnabled": true, "discountPrice": 3299.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-039', 'hpglow', 'HP-GLOW-PRECISION-PEN-V1', 'hp-glow-precision-pen-v1', 'HP Glow Precision Pen V1', 139900, 'PHP', 0, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1773749027431-ks6bth17rjm.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "storage": "Store at -20°C", "isSet": true, "inclusions": [{"name": "1x HP Glow Precision Pen V1", "qty": 1}, {"name": "1x Black Precision Pen Case", "qty": 1}, {"name": "2x UV Catridges", "qty": 1}, {"name": "30x Pen Needles (32g x 6mm/31g x 6m/ 31g x 8mm)", "qty": 1}], "variations": [{"name": "Black", "price": 1399}, {"name": "Pink", "price": 1399}, {"name": "Coral", "price": 1399}]}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-040', 'hpglow', 'APRIL-EXCLUSIVE-TIRZEPATIDE-60MG-TIRZEPATIDE-10MG', 'april-exclusive-tirzepatide-60mg-tirzepatide-10mg', '[𝗔𝗣𝗥𝗜𝗟 𝗘𝗫𝗖𝗟𝗨𝗦𝗜𝗩𝗘] TIRZEPATIDE 60mg + Tirzepatide 10mg', 569900, 'PHP', 0, 'draft', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1774846414587-qubn5wcg.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "featured": true, "purity": "99%", "storage": "Store at -20°C"}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-041', 'hpglow', 'FAT-BLASTER-LIPO-C', 'fat-blaster-lipo-c', 'Fat Blaster Lipo-C', 239900, 'PHP', 1, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1775976637299-0tjqd5efp0o.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "purity": "99%", "discountEnabled": true, "discountPrice": 1999.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;
INSERT INTO products (id, "tenantId", sku, slug, name, "priceCents", currency, stock, status, images, metadata)
VALUES ('hpglow-p-042', 'hpglow', 'GLOW-SCULPT-DUO-TIRZEPATIDE-30MG-GHK-CU-100MG-FREE-SHIPPING-NATIONWIDE', 'glow-sculpt-duo-tirzepatide-30mg-ghk-cu-100mg-free-shipping-nationwide', 'Glow Sculpt Duo (Tirzepatide 30mg & GHK-CU 100mg) - FREE SHIPPING NATIONWIDE', 554800, 'PHP', 4, 'active', '["https://rtsnxmatvbabdylsnuuh.supabase.co/storage/v1/object/public/menu-images/1778740277386-n2x6lgeg3n.png"]'::jsonb, '{"category": "All Products", "currencySymbol": "₱", "featured": true, "purity": "99%", "storage": "Store at -20°C", "discountEnabled": true, "discountPrice": 4799.0}'::jsonb)
ON CONFLICT ("tenantId", slug) DO NOTHING;

COMMIT;
-- End. tenant + branding + settings + 42 products. Variations packed into metadata.variations.
